In [7]:
import numpy as np

In [8]:
np.__version__

'1.18.1'

In [38]:
new_array = np.array([1, 2, 4, 10, 15])
new_array.shape

(5,)

In [11]:
for i in new_array:
    print (i)

1
2
4
10
15


In [12]:
new_array[0] = 10 
new_array

array([10,  2,  4, 10, 15])

In [39]:
second_array = np.eye(5)
second_array
second_array.ndim
second_array.shape

(5, 5)

In [17]:
new_array
new_array.ndim

1

In [19]:
second_array[1, 1] = 10
second_array


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
a = [1, 3]
b = a.copy()
a[0] = 10
b

[1, 3]

In [25]:
new_array = np.array([1, 2, 4, 10, 15, 3])
new_array.reshape(2, 3)

array([[ 1,  2,  4],
       [10, 15,  3]])

In [27]:
new_array = np.array([1, 2, 4, 10, 15, 3])
new_array + 10

array([11, 12, 14, 20, 25, 13])

In [28]:
new_array = np.array([1, 2, 4, 10, 15, 3])
new_array + ([1, 2, 4, 10, 15, 3])

array([ 2,  4,  8, 20, 30,  6])

In [48]:
n = int(input())
Z = np.zeros(n)
np.zeros(n, dtype=int)
Z = np.zeros((2,3))
Z < 0

n = int(input())
Z = np.zeros(n, dtype=int)
print(Z)


5
4
[0 0 0 0]


In [51]:
n = int(input())
Z = np.eye(n)
Z

3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
import numpy as np

np.random.seed(42)

l = input().split()
l = [int(el) for el in l]
n,m,l = l[0],l[1],l[2]

Z=np.random.random((n,m,l))
print(Z)

2 2 2


TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'